### ISSUE TITLE
GCSFS - Project Not Set, unable to get metrics.

### ISSUE THREAD

**Issue by tnjordan** [iterative/dvc-gs#35]
When using the action below:

```name: DVC TEST
on:
  push:
    branches:
      - dvc-debug
jobs:
  release:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: iterative/setup-dvc@v1
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DVC_SA }}
      - name: Metrics
        run: |
          dvc metrics show --all-tags data/output/metrics_eval.yaml --show-json > all_metrics.json
          dvc pull
```

The warning `gcsfs/core.py:285: UserWarning: GCS project not set - cannot list or create buckets` is displayed and the metrics are not retrieved. 

The dvc pull displays the same warning; however, the files are pulled in. 

This issue can be resolved by including the project name in the dvc config file.
```
[core] 
   remote = gcp
['remote "gcp"']
    projectname = project-name-gcp
    url = gs://*
```

This line was not previously needed.

It seems that the project name variable from the credentials file is not used, or the environment variables populated from the google authentication action [`google-github-actions/auth@v1`](https://github.com/google-github-actions/auth).

**Comment by efiop** [comment]
Looks like we just shouldn't set the project to `None` in https://github.com/iterative/dvc-gs/blob/e1aa778bb3982a204879c9f23328abb25391ca3a/dvc_gs/__init__.py#L25 and that should fix it. Would you be interested in trying that out and contributing a PR?

**Comment by efiop** [comment]
Overall i think gcsfs is in the wrong here, setting default project like this https://github.com/fsspec/gcsfs/blob/b3bbb21e6f3d9f2d76299ac0c0b2e90d2e7f96db/gcsfs/core.py#L256 is not good. But it is faster to just fix it on our side here by not setting a project if projectname is none. We will be able to live with that long term no problem.

**Comment by tnjordan** [comment]
PR Done: https://github.com/iterative/dvc-gs/pull/36

I was able to verify on my local machine that this update to the default causes gcsfs to work as intended.

**Comment by efiop** [comment]
@tnjordan Thank you for the research and the fix! 🙏
